uploads = []
generated = []

[[outputs]]
id = "EiXqjU1Jq28a0fS2Y2sOI"
uri = "file://nyumba-cpanel.zip"
type = "unspecified"
title = "nyumba-cpanel.zip (updated)"

[[outputs]]
id = "0MsCim-op4LuxdIlOct9I"
uri = "file://nyumba-netlify.zip"
type = "unspecified"
title = "Nyumba Magazine — Netlify Deploy"
