import { db } from "./index";
import {
  articlesTable, propertiesTable, professionalsTable, contractorsTable,
  suppliersTable, eventsTable, messagesTable, siteSettingsTable, homepageSliderTable
} from "./schema";

async function seed() {
  console.log("Seeding database...");

  // Articles
  await db.insert(articlesTable).values([
    {
      title: "Government Announces KSh 50 Billion Affordable Housing Initiative",
      content: `<p>The Ministry of Housing has unveiled ambitious plans to deliver 200,000 affordable housing units across Kenya by 2025, with a strong focus on urban centers such as Nairobi, Mombasa, Kisumu, and Nakuru.</p><p>Speaking at a press conference in Nairobi, Cabinet Secretary for Housing announced that the government will partner with private developers to fast-track construction of affordable units in key satellite towns around major cities.</p><p>The initiative is expected to create over 500,000 jobs in the construction sector and stimulate growth in related industries including cement, steel, and real estate services.</p>`,
      excerpt: "The Ministry of Housing unveils ambitious plans to deliver 200,000 affordable housing units across Kenya by 2025, with focus on urban centers.",
      featuredImage: "https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=800",
      category: "Policy & Regulations",
      author: "James Kiprotich",
      published: true,
      featured: true,
      views: 15420,
      readTime: "5 min read",
    },
    {
      title: "Revolutionary 3D Printing Technology Arrives in Nairobi",
      content: `<p>A local construction company has introduced cutting-edge 3D printing technology for faster and more efficient building construction, reducing costs by up to 40%.</p><p>The technology, which uses locally sourced materials, can construct a standard two-bedroom house in just 48 hours compared to the traditional 6-month timeline.</p><p>The company has already completed a pilot project in Ruaka, Kiambu County, and plans to scale operations across East Africa.</p>`,
      excerpt: "Local construction company introduces cutting-edge 3D printing technology for faster and more efficient building construction, reducing costs by 40%.",
      featuredImage: "https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=800",
      category: "Technology",
      author: "Mary Wanjiku",
      published: true,
      featured: true,
      views: 12350,
      readTime: "6 min read",
    },
    {
      title: "Cement Prices Drop 15% as New Factory Opens in Machakos",
      content: `<p>The opening of a new cement manufacturing plant in Machakos County is expected to reduce construction costs significantly across Kenya.</p><p>The plant, which cost KSh 8 billion to construct, has an annual capacity of 1.5 million tonnes and will create direct employment for over 800 workers.</p><p>Industry analysts predict that the increased supply will bring cement prices down from an average of KSh 720 per 50kg bag to approximately KSh 620 by the third quarter of 2024.</p>`,
      excerpt: "The opening of a new cement manufacturing plant is expected to reduce construction costs and boost local development projects across the region.",
      featuredImage: "https://images.pexels.com/photos/1216564/pexels-photo-1216564.jpeg?auto=compress&cs=tinysrgb&w=800",
      category: "Market Updates",
      author: "Peter Mwangi",
      published: true,
      featured: false,
      views: 8920,
      readTime: "4 min read",
    },
    {
      title: "Green Building Certification Program Launched in Kenya",
      content: `<p>The Kenya Green Building Society has introduced new certification standards to promote environmentally sustainable construction practices nationwide.</p><p>The new Green Star Kenya rating system evaluates buildings across nine categories including energy efficiency, water conservation, indoor environment quality, and materials selection.</p><p>Buildings certified under the new system are expected to use 30-50% less energy and 40% less water compared to conventional buildings.</p>`,
      excerpt: "Kenya Green Building Society introduces new certification standards to promote environmentally sustainable construction practices nationwide.",
      featuredImage: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800",
      category: "Policy & Regulations",
      author: "Grace Njeri",
      published: true,
      featured: false,
      views: 6780,
      readTime: "7 min read",
    },
    {
      title: "Nairobi Expressway Phase 2 Construction Begins",
      content: `<p>The second phase of the Nairobi Expressway project officially commenced this week, promising to ease traffic congestion along one of the city's busiest corridors.</p><p>The 27-kilometre extension will connect Mlolongo to the existing expressway at Westlands, passing through major commercial nodes including South B, South C, and Langata.</p><p>The project is expected to be completed within 36 months and will reduce travel time between Nairobi's CBD and Jomo Kenyatta International Airport to under 20 minutes.</p>`,
      excerpt: "The second phase of the Nairobi Expressway project officially commences, promising to ease traffic congestion and boost economic growth.",
      featuredImage: "https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg?auto=compress&cs=tinysrgb&w=800",
      category: "Major Projects",
      author: "David Ochieng",
      published: true,
      featured: false,
      views: 9150,
      readTime: "8 min read",
    },
    {
      title: "Smart Home Technology Adoption Rises Among Kenyan Homeowners",
      content: `<p>A new survey reveals that smart home technology adoption among Kenyan urban homeowners has doubled in the past two years, driven by falling device costs and improved internet connectivity.</p><p>Over 35% of new residential developments in Nairobi's upmarket suburbs now include integrated smart home systems as a standard feature.</p><p>Popular features include automated lighting, smart security systems, solar energy management, and water conservation technologies.</p>`,
      excerpt: "Survey reveals smart home technology adoption in Kenya has doubled in two years as costs fall and internet connectivity improves nationwide.",
      featuredImage: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800",
      category: "Technology",
      author: "Susan Kamau",
      published: true,
      featured: false,
      views: 5430,
      readTime: "5 min read",
    },
  ]).onConflictDoNothing();
  console.log("✓ Articles seeded");

  // Properties
  await db.insert(propertiesTable).values([
    {
      title: "Modern Executive Villa - Karen",
      description: "Stunning modern villa with panoramic views, premium finishes, and smart home technology. This exceptional property features an open-plan design with floor-to-ceiling windows, gourmet kitchen, private swimming pool, and beautifully landscaped gardens on a half-acre plot.",
      price: "45000000",
      location: "Karen, Nairobi",
      propertyType: "residential",
      bedrooms: 5,
      bathrooms: 4,
      area: "4200",
      images: ["https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800"],
      amenities: ["Swimming Pool", "Garden", "Garage", "Security", "Generator", "CCTV", "Borehole"],
      contactName: "Sarah Kimani",
      contactPhone: "+254 722 123 456",
      contactEmail: "sarah@premiumproperties.co.ke",
      agent: "Sarah Kimani",
      published: true,
      featured: true,
      views: 342,
    },
    {
      title: "Luxury Penthouse - Westlands",
      description: "Exclusive penthouse with stunning city views and premium building amenities. Located in the heart of Westlands, this exquisite penthouse offers the ultimate urban living experience with breathtaking views of Nairobi's skyline.",
      price: "35000000",
      location: "Westlands, Nairobi",
      propertyType: "residential",
      bedrooms: 3,
      bathrooms: 3,
      area: "2800",
      images: ["https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800"],
      amenities: ["Gym", "Rooftop Terrace", "Concierge", "Parking", "Elevator"],
      contactName: "Michael Ochieng",
      contactPhone: "+254 733 234 567",
      contactEmail: "michael@luxuryhomes.co.ke",
      agent: "Michael Ochieng",
      published: true,
      featured: true,
      views: 289,
    },
    {
      title: "Family Home - Kiambu Road",
      description: "Perfect family home in a quiet, secure neighborhood with a large compound and modern amenities. The property features a well-maintained garden, ample parking, and is within walking distance of top-tier schools and shopping centres.",
      price: "18000000",
      location: "Kiambu Road, Nairobi",
      propertyType: "residential",
      bedrooms: 4,
      bathrooms: 3,
      area: "3200",
      images: ["https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=800"],
      amenities: ["Garden", "Parking", "Security", "Borehole", "Playground"],
      contactName: "Grace Wanjiku",
      contactPhone: "+254 711 345 678",
      contactEmail: "grace@familyhomes.co.ke",
      agent: "Grace Wanjiku",
      published: true,
      featured: false,
      views: 156,
    },
    {
      title: "Commercial Office Space - CBD",
      description: "Prime commercial office space in Nairobi's Central Business District, ideal for corporate headquarters or professional services firms. The space comes with modern fittings, high-speed internet infrastructure, and 24-hour security.",
      price: "25000000",
      location: "CBD, Nairobi",
      propertyType: "commercial",
      bedrooms: 0,
      bathrooms: 2,
      area: "1500",
      images: ["https://images.pexels.com/photos/416405/pexels-photo-416405.jpeg?auto=compress&cs=tinysrgb&w=800"],
      amenities: ["Parking", "Elevator", "Generator", "Security", "CCTV"],
      contactName: "John Mwenda",
      contactPhone: "+254 722 567 890",
      contactEmail: "john@commercialproperties.co.ke",
      agent: "John Mwenda",
      published: true,
      featured: false,
      views: 98,
    },
    {
      title: "Half-Acre Plot - Ruaka",
      description: "Prime land available for residential or commercial development in Ruaka, one of Nairobi's fastest growing suburbs. The plot has road frontage, is fully serviced with water and electricity, and is in a serene gated community.",
      price: "8500000",
      location: "Ruaka, Kiambu County",
      propertyType: "land",
      bedrooms: 0,
      bathrooms: 0,
      area: "2000",
      images: ["https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=800"],
      amenities: ["Road Frontage", "Water Connection", "Electricity", "Title Deed"],
      contactName: "Anne Njoroge",
      contactPhone: "+254 733 678 901",
      contactEmail: "anne@landkenya.co.ke",
      agent: "Anne Njoroge",
      published: true,
      featured: false,
      views: 211,
    },
    {
      title: "2-Bedroom Apartment for Rent - Kilimani",
      description: "Modern, fully furnished 2-bedroom apartment available for rent in the leafy Kilimani suburb. Features contemporary interiors, high-speed WiFi, secure parking, and access to a swimming pool and gym.",
      price: "120000",
      location: "Kilimani, Nairobi",
      propertyType: "rental",
      bedrooms: 2,
      bathrooms: 2,
      area: "1100",
      images: ["https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=800"],
      amenities: ["Swimming Pool", "Gym", "Parking", "WiFi", "Security", "Balcony"],
      contactName: "Tom Kamau",
      contactPhone: "+254 700 234 567",
      contactEmail: "tom@rentalkenya.co.ke",
      agent: "Tom Kamau",
      published: true,
      featured: true,
      views: 178,
    },
  ]).onConflictDoNothing();
  console.log("✓ Properties seeded");

  // Professionals
  await db.insert(professionalsTable).values([
    {
      name: "Dr. Sarah Mwangi",
      profession: "Architect",
      company: "Mwangi & Associates Architecture",
      location: "Nairobi, Kenya",
      description: "Award-winning architect specializing in sustainable and eco-friendly building designs with over 15 years of experience in commercial and residential projects across East Africa.",
      specialties: ["Sustainable Design", "Commercial Buildings", "Green Architecture", "Urban Planning"],
      experienceYears: 15,
      hourlyRate: "5000",
      certifications: ["LEED AP", "RIBA", "Board of Registration of Architects and Quantity Surveyors"],
      image: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=400",
      contactPhone: "+254 722 123 456",
      contactEmail: "sarah@mwangiarch.co.ke",
      website: "www.mwangiarchitecture.co.ke",
      verified: true,
      published: true,
      rating: "4.9",
      reviews: 127,
      projects: 89,
    },
    {
      name: "Eng. Michael Ochieng",
      profession: "Structural Engineer",
      company: "Ochieng Structural Consultants",
      location: "Nairobi, Kenya",
      description: "Experienced structural engineer with expertise in high-rise buildings and complex infrastructure projects across East Africa. Registered with the Engineers Board of Kenya.",
      specialties: ["High-rise Buildings", "Bridge Design", "Seismic Analysis", "Steel Structures"],
      experienceYears: 12,
      hourlyRate: "4500",
      certifications: ["PE License", "IStructE", "EBK Registration"],
      image: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400",
      contactPhone: "+254 733 234 567",
      contactEmail: "michael@ochiengstructural.co.ke",
      verified: true,
      published: true,
      rating: "4.8",
      reviews: 94,
      projects: 156,
    },
    {
      name: "Grace Wanjiku, QS",
      profession: "Quantity Surveyor",
      company: "Wanjiku Cost Consultancy",
      location: "Nairobi, Kenya",
      description: "Professional quantity surveyor with expertise in cost management, contract administration, and value engineering for large-scale construction projects in Kenya and East Africa.",
      specialties: ["Cost Estimation", "Contract Management", "Risk Assessment", "Value Engineering"],
      experienceYears: 10,
      hourlyRate: "3500",
      certifications: ["RICS", "BORAQS", "Project Management Professional"],
      image: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400",
      contactPhone: "+254 711 345 678",
      contactEmail: "grace@wanjikuqs.co.ke",
      verified: true,
      published: true,
      rating: "4.7",
      reviews: 78,
      projects: 67,
    },
    {
      name: "Peter Kamau",
      profession: "Civil Engineer",
      company: "Kamau Civil Engineering Ltd",
      location: "Nairobi, Kenya",
      description: "Civil engineer specializing in road construction, drainage systems, and infrastructure development projects across Kenya. Over 14 years of field experience.",
      specialties: ["Road Construction", "Drainage Systems", "Site Development", "Infrastructure Planning"],
      experienceYears: 14,
      hourlyRate: "4000",
      certifications: ["EBK Registration", "IEK Member"],
      image: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=400",
      contactPhone: "+254 722 456 789",
      contactEmail: "peter@kamauce.co.ke",
      verified: true,
      published: true,
      rating: "4.6",
      reviews: 52,
      projects: 43,
    },
  ]).onConflictDoNothing();
  console.log("✓ Professionals seeded");

  // Contractors
  await db.insert(contractorsTable).values([
    {
      name: "James Wilson",
      company: "Wilson Construction Group",
      contractorType: "General Contractor",
      location: "Nairobi, Kenya",
      description: "Licensed general contractor with extensive experience in residential and commercial construction projects across Kenya. Known for delivering quality projects on time and within budget.",
      services: ["Residential Construction", "Commercial Buildings", "Renovations", "Custom Homes"],
      licenseNumber: "GC-2024-001",
      insurance: true,
      bond: true,
      employees: 45,
      projectsCompleted: 234,
      experienceYears: 18,
      image: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=400",
      contactPhone: "+254 722 456 789",
      contactEmail: "james@wilsonconst.co.ke",
      verified: true,
      published: true,
      rating: "4.9",
      reviews: 156,
    },
    {
      name: "Mary Njeri",
      company: "PowerTech Electrical Solutions",
      contractorType: "Electrical Contractor",
      location: "Nairobi, Kenya",
      description: "Certified electrical contractor specializing in residential and commercial electrical installations, solar energy systems, and smart home wiring.",
      services: ["Electrical Installations", "Solar Systems", "Smart Home Wiring", "Generator Installation"],
      licenseNumber: "EC-2024-045",
      insurance: true,
      bond: false,
      employees: 22,
      projectsCompleted: 189,
      experienceYears: 12,
      image: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=400",
      contactPhone: "+254 733 567 890",
      contactEmail: "mary@powertechke.co.ke",
      verified: true,
      published: true,
      rating: "4.8",
      reviews: 112,
    },
    {
      name: "Robert Kamau",
      company: "AquaFlow Plumbing Services",
      contractorType: "Plumbing Contractor",
      location: "Nairobi, Kenya",
      description: "Professional plumbing contractor providing comprehensive water, drainage, and sanitation solutions for residential and commercial properties across Nairobi and its environs.",
      services: ["Plumbing Installation", "Water Systems", "Drainage Solutions", "Bathroom Fitting"],
      licenseNumber: "PC-2024-089",
      insurance: true,
      bond: false,
      employees: 18,
      projectsCompleted: 145,
      experienceYears: 9,
      image: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400",
      contactPhone: "+254 700 678 901",
      contactEmail: "robert@aquaflowke.co.ke",
      verified: true,
      published: true,
      rating: "4.7",
      reviews: 87,
    },
  ]).onConflictDoNothing();
  console.log("✓ Contractors seeded");

  // Suppliers
  await db.insert(suppliersTable).values([
    {
      companyName: "East African Portland Cement",
      contactPerson: "Robert Kimani",
      categories: ["Cement & Concrete"],
      products: ["Portland Cement", "Ready Mix Concrete", "Cement Blocks", "Precast Products"],
      description: "Leading cement manufacturer in East Africa providing high-quality cement and concrete products for construction projects of all sizes.",
      location: "Nairobi, Kenya",
      website: "www.eaportland.co.ke",
      establishedYear: 1999,
      employees: 150,
      deliveryRadius: 50,
      minOrderAmount: "50000",
      paymentTerms: "30 days",
      contactPhone: "+254 722 123 456",
      contactEmail: "robert@eaportland.co.ke",
      verified: true,
      published: true,
      rating: "4.8",
      reviews: 234,
    },
    {
      companyName: "Kenya Steel Works",
      contactPerson: "Mary Wanjiku",
      categories: ["Steel & Metal"],
      products: ["Structural Steel", "Steel Bars", "Roofing Sheets", "Wire Mesh"],
      description: "Leading supplier of high-quality steel products for construction, manufacturing, and industrial applications across East Africa.",
      location: "Mombasa, Kenya",
      website: "www.kenyasteel.co.ke",
      establishedYear: 2005,
      employees: 89,
      deliveryRadius: 100,
      minOrderAmount: "100000",
      paymentTerms: "45 days",
      contactPhone: "+254 733 234 567",
      contactEmail: "mary@kenyasteel.co.ke",
      verified: true,
      published: true,
      rating: "4.7",
      reviews: 178,
    },
    {
      companyName: "SolarTech Africa",
      contactPerson: "James Otieno",
      categories: ["Electrical Supplies", "Solar Energy"],
      products: ["Solar Panels", "Inverters", "Batteries", "Solar Water Heaters", "LED Lighting"],
      description: "Premier supplier of solar energy solutions and electrical supplies for residential, commercial, and industrial applications across Kenya.",
      location: "Nairobi, Kenya",
      website: "www.solartechafrica.co.ke",
      establishedYear: 2012,
      employees: 65,
      deliveryRadius: 200,
      minOrderAmount: "30000",
      paymentTerms: "30 days",
      contactPhone: "+254 700 345 678",
      contactEmail: "james@solartechafrica.co.ke",
      verified: true,
      published: true,
      rating: "4.9",
      reviews: 321,
    },
  ]).onConflictDoNothing();
  console.log("✓ Suppliers seeded");

  // Events
  await db.insert(eventsTable).values([
    {
      title: "Kenya Construction Expo 2025",
      description: "The largest construction industry exhibition in East Africa featuring the latest technologies, materials, and innovations from leading manufacturers and suppliers.",
      category: "Exhibition",
      eventDate: "2025-03-15",
      eventTime: "09:00 AM",
      endDate: "2025-03-17",
      location: "KICC, Nairobi",
      venue: "Kenyatta International Convention Centre",
      price: "2500",
      image: "https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=800",
      organizer: "Kenya Association of Building & Civil Engineering Contractors",
      attendees: 5000,
      speakers: ["Dr. Sarah Mwangi", "Eng. Michael Ochieng", "Arch. Grace Wanjiku"],
      featured: true,
      status: "upcoming",
      website: "https://kenyaconstructionexpo.com",
      published: true,
    },
    {
      title: "Sustainable Building Materials Conference",
      description: "Exploring eco-friendly construction materials and sustainable building practices for the future of Kenya's built environment.",
      category: "Conference",
      eventDate: "2025-04-28",
      eventTime: "08:30 AM",
      endDate: "2025-04-28",
      location: "Serena Hotel, Nairobi",
      venue: "Serena Hotel Conference Center",
      price: "3500",
      image: "https://images.pexels.com/photos/416917/pexels-photo-416917.jpeg?auto=compress&cs=tinysrgb&w=800",
      organizer: "Green Building Society of Kenya",
      attendees: 800,
      speakers: ["Prof. Jane Wambua", "Dr. Tom Kariuki"],
      featured: true,
      status: "upcoming",
      published: true,
    },
    {
      title: "Real Estate Investment Summit",
      description: "Connect with top investors, developers, and real estate professionals at Kenya's premier property investment event.",
      category: "Conference",
      eventDate: "2025-05-10",
      eventTime: "09:00 AM",
      endDate: "2025-05-10",
      location: "Radisson Blu, Nairobi",
      venue: "Radisson Blu Upper Hill Hotel",
      price: "5000",
      image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
      organizer: "Kenya Property Developers Association",
      attendees: 1200,
      speakers: [],
      featured: false,
      status: "upcoming",
      published: true,
    },
  ]).onConflictDoNothing();
  console.log("✓ Events seeded");

  // Messages
  await db.insert(messagesTable).values([
    { name: "Mary Njeri", email: "mary@example.com", subject: "Property Inquiry - Karen Villa", message: "I am very interested in the villa listing in Karen. Could you please arrange a viewing for this Saturday? I am pre-approved for financing.", readStatus: false },
    { name: "James Ochieng", email: "james@example.com", subject: "Partnership Opportunity", message: "We would like to discuss a potential partnership for our upcoming commercial development in Nairobi. Please let us know the best time to connect.", readStatus: true },
    { name: "Patricia Waweru", email: "patricia@example.com", subject: "Professional Listing Enquiry", message: "I am a registered architect interested in listing my services on your platform. What are the requirements and fees?", readStatus: false },
  ]).onConflictDoNothing();
  console.log("✓ Messages seeded");

  // Site Settings
  await db.insert(siteSettingsTable).values([
    { settingKey: "site_name", settingValue: "Nyumba" },
    { settingKey: "site_description", settingValue: "Kenya's Premier Construction Industry Magazine" },
    { settingKey: "contact_email", settingValue: "info@nyumba.co.ke" },
    { settingKey: "contact_phone", settingValue: "+254 700 123 456" },
    { settingKey: "address", settingValue: "Westlands, Nairobi, Kenya" },
    { settingKey: "facebook_url", settingValue: "https://facebook.com/nyumbamagazine" },
    { settingKey: "twitter_url", settingValue: "https://twitter.com/nyumba_mag" },
    { settingKey: "linkedin_url", settingValue: "https://linkedin.com/company/nyumba" },
    { settingKey: "instagram_url", settingValue: "https://instagram.com/nyumba_magazine" },
  ]).onConflictDoNothing();
  console.log("✓ Site settings seeded");

  // Slider
  await db.insert(homepageSliderTable).values([
    { title: "Construction Materials Catalog 2025", description: "Complete guide to premium building materials", fileType: "pdf", filePath: "/catalogs/materials-2025.pdf", imagePath: "https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=800", active: true, sortOrder: 1 },
    { title: "Modern Architecture Trends", description: "Latest architectural trends and innovations in Kenya", fileType: "image", filePath: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800", imagePath: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800", active: true, sortOrder: 2 },
  ]).onConflictDoNothing();
  console.log("✓ Slider items seeded");

  console.log("✅ Database seeding complete!");
}

seed().catch(console.error).finally(() => process.exit(0));
